[package]
name = "mipidsi-async"
version = "0.1.0"
edition = "2021"
authors = ["Kamitai"]
description = "Async framebuffer display driver for MIPI DCS displays with DMA support"
license = "MIT"
repository = "https://github.com/Kamitai6/mipidsi-async"
keywords = ["embedded", "display", "mipi", "dcs", "async", "dma"]
categories = ["embedded", "no-std", "hardware-support"]
readme = "README.md"

[dependencies]
embedded-graphics-core = "0.4"
embedded-hal = "1.0"

[dev-dependencies]
embedded-graphics = "0.8"

[features]
default = []
defmt = []
