[package]
name = "esp-display-interface"
version = "0.1.0"
edition = "2021"
authors = ["Kamitai"]
description = "ESP32 SPI DMA interface implementation for mipidsi-async"
license = "MIT"
repository = "https://github.com/Kamitai6/esp-display-interface"
keywords = ["embedded", "esp32", "display", "spi", "dma"]
categories = ["embedded", "no-std", "hardware-support"]

[dependencies]
mipidsi-async = {version = "0.1", path = "../mipidsi-async"}
esp-hal = { version = "1.0", default-features = false }
paste = "1.0"

[features]
default = []

